// "use client"; // 서버 컴포넌트에서 사용 불가
import Link from "next/link";
import './globals.css'
import { Control } from './Control';
export const metadata = {
    title: 'Web Tutorial',
    description: 'Generated by cpk78',
}
export default async function RootLayout({children}) {
    const resp = await fetch('http://localhost:9999/topics', {cache: 'no-store'})
    const topics = await resp.json();
    return (
        <html>
            <body>
            <h1><Link href="/">Web</Link></h1>
            <ol>
                {/*<li><Link href="/read/1">1.html</Link></li>*/}
                {/*<li><Link href="/read/2">2.css</Link></li>*/}
                {topics.map(topic=>{
                    return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
                })}
            </ol>
            {children}
            <Control></Control>
            </body>
        </html>
    )
}
