// "use client"; // 서버 컴포넌트에서 사용 불가
import Link from "next/link";
import './globals.css'
import {Control} from './Control';

export const metadata = {
    title: 'Next.js Sample',
    description: 'Generated by cpk78',
}
export default async function RootLayout({children}) {
    const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + 'topics', {cache: 'no-store'})
    const topics = await resp.json();
    return (
        <html>
        <body>
        <Link href="/">HOME</Link>

        <ol>
            {topics.map(topic => {
                return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
            })}
        </ol>

        {children}

        <Control></Control>

        </body>
        </html>
    )
}
