// "use client"; // 서버 컴포넌트에서 사용 불가
import Link from "next/link";
import './globals.css'
import {Control} from './Control';

export const metadata = {
    title: 'Next.js Sample',
    description: 'Generated by cpk78',
}
export default async function RootLayout({children}) {
    const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + 'topics', {cache: 'no-store'}) // or { next: { revalidate: 3600 } })
    const topics = await resp.json();
    return (
        <html>
        <body>
        <button class="button"><Link href="/">HOME</Link></button>

        {topics.map(topic => {
            return <button class="button" key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></button>
        })}

        <Control></Control>

        {children}



        </body>
        </html>
    )
}
